sudo: required

#branches:
#  only:
#  - master

services:
  - docker

before_install:
  - docker build -t boryslavkrymeniuk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run boryslavkrymeniuk/react-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t boryslavkrymeniuk/multi-client ./client
  - docker build -t boryslavkrymeniuk/multi-server ./server
  - docker build -t boryslavkrymeniuk/multi-worker ./worker
  - docker build -t boryslavkrymeniuk/multi-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and put them to the Docker Hub
  -docker push boryslavkrymeniuk/multi-client
  -docker push boryslavkrymeniuk/multi-server
  -docker push boryslavkrymeniuk/multi-worker
  -docker push boryslavkrymeniuk/multi-nginx
  

